name: Release

on:
  release:
    types: [created]

jobs:
  #builds and deploys libs to github packages
  call-workflow-maven-install-deploy:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-install-deploy-lib.yml@main
    with:
      package-version: ${{ github.event.release.tag_name }}
      deployment-repository: ${{ github.repository }}
      java-version: 21
      sbom-path: ./
    secrets: inherit

