name: Maven build and test

on:
  push:
    branches: [main]

jobs:
  call-workflow-maven-build:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-build.yml@main
    with:
      java-version: 21
    secrets: inherit

